/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Blink',
            'microPythonEsp32S3.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32S3.examples.button.name': 'Button',
            'microPythonEsp32S3.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32S3.examples.fade.name': 'Fade',
            'microPythonEsp32S3.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32S3.examples.knob.name': 'Knob',
            'microPythonEsp32S3.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32S3.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32S3.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        },
        'ru': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Мигание',
            'microPythonEsp32S3.examples.blink.description': 'Заставьте встроенный светодиод мигать.',
            'microPythonEsp32S3.examples.button.name': 'Кнопка',
            'microPythonEsp32S3.examples.button.description': 'Зажигайте светодиод, пока нажата кнопка.',
            'microPythonEsp32S3.examples.fade.name': 'Плавное затухание',
            'microPythonEsp32S3.examples.fade.description': 'Плавное затухание светодиода с помощью ШИМ.',
            'microPythonEsp32S3.examples.knob.name': 'Регулятор',
            'microPythonEsp32S3.examples.knob.description': 'Регулировка яркости светодиода с помощью потенциометра.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Развертка серво',
            'microPythonEsp32S3.examples.servoSweep.description': 'Поворот серво вперед и назад между 0° и 180°.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Печать в консоль',
            'microPythonEsp32S3.examples.consolePrint.description': 'Печать сообщений в REPL-консоль MicroPython.'
        },
        'zh-cn': {
            'microPythonEsp32S3.description': '搭载双核 Xtensa LX7 MCU 的 Wi-Fi 与蓝牙控制板。',
            'microPythonEsp32S3.examples.blink.name': '闪烁',
            'microPythonEsp32S3.examples.blink.description': '让板载 LED 闪烁。',
            'microPythonEsp32S3.examples.button.name': '按键',
            'microPythonEsp32S3.examples.button.description': '按住按键时点亮 LED。',
            'microPythonEsp32S3.examples.fade.name': '呼吸灯',
            'microPythonEsp32S3.examples.fade.description': '用 PWM 让 LED 缓缓变亮再渐渐变暗。',
            'microPythonEsp32S3.examples.knob.name': '电位器调光',
            'microPythonEsp32S3.examples.knob.description': '用电位器调节 LED 的亮度。',
            'microPythonEsp32S3.examples.servoSweep.name': '舵机来回扫描',
            'microPythonEsp32S3.examples.servoSweep.description': '让舵机在 0° 到 180° 之间来回转动。',
            'microPythonEsp32S3.examples.consolePrint.name': '控制台输出',
            'microPythonEsp32S3.examples.consolePrint.description': '把消息打印到 MicroPython REPL 控制台。'
        },
        'zh-tw': {
            'microPythonEsp32S3.description': '搭載雙核 Xtensa LX7 MCU 的 Wi-Fi 與藍牙控制板。',
            'microPythonEsp32S3.examples.blink.name': '閃爍',
            'microPythonEsp32S3.examples.blink.description': '讓板載 LED 閃爍。',
            'microPythonEsp32S3.examples.button.name': '按鍵',
            'microPythonEsp32S3.examples.button.description': '按住按鍵時點亮 LED。',
            'microPythonEsp32S3.examples.fade.name': '呼吸燈',
            'microPythonEsp32S3.examples.fade.description': '用 PWM 讓 LED 緩緩變亮再漸漸變暗。',
            'microPythonEsp32S3.examples.knob.name': '電位器調光',
            'microPythonEsp32S3.examples.knob.description': '用電位器調節 LED 的亮度。',
            'microPythonEsp32S3.examples.servoSweep.name': '舵機來回掃描',
            'microPythonEsp32S3.examples.servoSweep.description': '讓舵機在 0° 到 180° 之間來回轉動。',
            'microPythonEsp32S3.examples.consolePrint.name': '終端輸出',
            'microPythonEsp32S3.examples.consolePrint.description': '將訊息列印到 MicroPython REPL 終端。'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp32S3.modeMenu.input': '输入',
            'microPythonEsp32S3.modeMenu.output': '输出',
            'microPythonEsp32S3.modeMenu.inputPullup': '上拉输入',
            'microPythonEsp32S3.modeMenu.inputPulldown': '下拉输入',
            'microPythonEsp32S3.levelMenu.high': '高',
            'microPythonEsp32S3.levelMenu.low': '低',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonEsp32S3.InterrupModeMenu.low': '低电平',
            'microPythonEsp32S3.InterrupModeMenu.high': '高电平',
            'microPythonEsp32S3.eolMenu.warp': '换行',
            'microPythonEsp32S3.eolMenu.noWarp': '不换行',
            'microPythonEsp32S3.category.pins': '引脚',
            'microPythonEsp32S3.pins.setPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': '设置 PWM 引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': '读取模拟引脚 [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': '读取触摸引脚 [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': '设置舵机引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonEsp32S3.category.console': '串口',
            'microPythonEsp32S3.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonEsp32S3.modeMenu.input': '輸入',
            'microPythonEsp32S3.modeMenu.output': '輸出',
            'microPythonEsp32S3.modeMenu.inputPullup': '上拉輸入',
            'microPythonEsp32S3.modeMenu.inputPulldown': '下拉輸入',
            'microPythonEsp32S3.levelMenu.high': '高',
            'microPythonEsp32S3.levelMenu.low': '低',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonEsp32S3.InterrupModeMenu.low': '低電平',
            'microPythonEsp32S3.InterrupModeMenu.high': '高電平',
            'microPythonEsp32S3.eolMenu.warp': '換行',
            'microPythonEsp32S3.eolMenu.noWarp': '不換行',
            'microPythonEsp32S3.category.pins': '引腳',
            'microPythonEsp32S3.pins.setPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': '設定 PWM 引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': '讀取類比引腳 [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': '讀取觸控引腳 [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': '設定伺服引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonEsp32S3.category.console': '串列',
            'microPythonEsp32S3.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
