/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Blink',
            'microPythonEsp32S3.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32S3.examples.button.name': 'Button',
            'microPythonEsp32S3.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32S3.examples.fade.name': 'Fade',
            'microPythonEsp32S3.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32S3.examples.knob.name': 'Knob',
            'microPythonEsp32S3.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32S3.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32S3.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        },
        'ru': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Blink',
            'microPythonEsp32S3.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32S3.examples.button.name': 'Button',
            'microPythonEsp32S3.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32S3.examples.fade.name': 'Fade',
            'microPythonEsp32S3.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32S3.examples.knob.name': 'Knob',
            'microPythonEsp32S3.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32S3.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32S3.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        },
        'zh-cn': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Blink',
            'microPythonEsp32S3.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32S3.examples.button.name': 'Button',
            'microPythonEsp32S3.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32S3.examples.fade.name': 'Fade',
            'microPythonEsp32S3.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32S3.examples.knob.name': 'Knob',
            'microPythonEsp32S3.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32S3.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32S3.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        },
        'zh-tw': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.',
            'microPythonEsp32S3.examples.blink.name': 'Blink',
            'microPythonEsp32S3.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonEsp32S3.examples.button.name': 'Button',
            'microPythonEsp32S3.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonEsp32S3.examples.fade.name': 'Fade',
            'microPythonEsp32S3.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonEsp32S3.examples.knob.name': 'Knob',
            'microPythonEsp32S3.examples.knob.description': 'Control LED brightness with a potentiometer.',
            'microPythonEsp32S3.examples.servoSweep.name': 'Servo Sweep',
            'microPythonEsp32S3.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonEsp32S3.examples.consolePrint.name': 'Console Print',
            'microPythonEsp32S3.examples.consolePrint.description': 'Print messages to the MicroPython REPL console.'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-tw': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
