/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.'
        },
        'ru': {
            'microPythonEsp32S3.description': 'Wi-Fi & Bluetooth control board powered by a dual-core Xtensa LX7 MCU.'
        },
        'zh-cn': {
            'microPythonEsp32S3.description': '搭载双核 Xtensa LX7 MCU 的 Wi-Fi 与蓝牙控制板。'
        },
        'zh-tw': {
            'microPythonEsp32S3.description': '搭載雙核 Xtensa LX7 MCU 的 Wi-Fi 與藍牙控制板。'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp32S3.modeMenu.input': 'input',
            'microPythonEsp32S3.modeMenu.output': 'output',
            'microPythonEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonEsp32S3.levelMenu.high': 'high',
            'microPythonEsp32S3.levelMenu.low': 'low',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp32S3.InterrupModeMenu.low': 'low level',
            'microPythonEsp32S3.InterrupModeMenu.high': 'high level',
            'microPythonEsp32S3.eolMenu.warp': 'warp',
            'microPythonEsp32S3.eolMenu.noWarp': 'no-warp',
            'microPythonEsp32S3.category.pins': 'Pins',
            'microPythonEsp32S3.pins.esp32SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp32S3.pins.esp32SetDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp32S3.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.esp32ReadDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp32S3.pins.esp32ReadAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp32S3.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp32S3.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp32S3.category.console': 'Console',
            'microPythonEsp32S3.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp32S3.modeMenu.input': '输入',
            'microPythonEsp32S3.modeMenu.output': '输出',
            'microPythonEsp32S3.modeMenu.inputPullup': '上拉输入',
            'microPythonEsp32S3.modeMenu.inputPulldown': '下拉输入',
            'microPythonEsp32S3.levelMenu.high': '高',
            'microPythonEsp32S3.levelMenu.low': '低',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonEsp32S3.InterrupModeMenu.low': '低电平',
            'microPythonEsp32S3.InterrupModeMenu.high': '高电平',
            'microPythonEsp32S3.eolMenu.warp': '换行',
            'microPythonEsp32S3.eolMenu.noWarp': '不换行',
            'microPythonEsp32S3.category.pins': '引脚',
            'microPythonEsp32S3.pins.esp32SetPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonEsp32S3.pins.esp32SetDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonEsp32S3.pins.esp32SetPwmOutput': '设置 PWM 引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp32S3.pins.esp32ReadDigitalPin': '读取数字引脚 [PIN]',
            'microPythonEsp32S3.pins.esp32ReadAnalogPin': '读取模拟引脚 [PIN]',
            'microPythonEsp32S3.pins.esp32ReadTouchPin': '读取触摸引脚 [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': '设置舵机引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp32S3.pins.esp32AttachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonEsp32S3.category.console': '串口',
            'microPythonEsp32S3.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonEsp32S3.modeMenu.input': '輸入',
            'microPythonEsp32S3.modeMenu.output': '輸出',
            'microPythonEsp32S3.modeMenu.inputPullup': '上拉輸入',
            'microPythonEsp32S3.modeMenu.inputPulldown': '下拉輸入',
            'microPythonEsp32S3.levelMenu.high': '高',
            'microPythonEsp32S3.levelMenu.low': '低',
            'microPythonEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp32S3.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonEsp32S3.InterrupModeMenu.low': '低電平',
            'microPythonEsp32S3.InterrupModeMenu.high': '高電平',
            'microPythonEsp32S3.eolMenu.warp': '換行',
            'microPythonEsp32S3.eolMenu.noWarp': '不換行',
            'microPythonEsp32S3.category.pins': '引腳',
            'microPythonEsp32S3.pins.esp32SetPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonEsp32S3.pins.esp32SetDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonEsp32S3.pins.esp32SetPwmOutput': '設定 PWM 引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp32S3.pins.esp32ReadDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonEsp32S3.pins.esp32ReadAnalogPin': '讀取類比引腳 [PIN]',
            'microPythonEsp32S3.pins.esp32ReadTouchPin': '讀取觸控引腳 [PIN]',
            'microPythonEsp32S3.pins.setServoOutput': '設定伺服引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp32S3.pins.esp32AttachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonEsp32S3.category.console': '串列',
            'microPythonEsp32S3.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonEsp32S3.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
